export const ar = {
  brand: "يلا مكسب",
  tagline: "عروض بالقرب منك",
  heroPitch: "اكتشف صفقات المتاجر القريبة منك، تابع متاجرك المفضّلة، واحفظ العروض قبل أن تنتهي.",
  heroShot: "لقطة من تطبيق يلا مكسب — قائمة العروض القريبة",
  downloadCta: "حمّل التطبيق",
  navDownload: "حمّل التطبيق",
  androidChip: "متاح على أندرويد",
  // value strip
  valueNear: "قريب منك",
  valueFree: "مجاني",
  valueInstant: "فوري",
  // shoppers
  shoppersTitle: "للزبائن",
  shoppersHeadline: "كل عروض جيرانك بمكان واحد",
  shoppersPoints: ["عروض قريبة منك", "تابع متاجرك المفضّلة", "احفظ العروض وعُد إليها"],
  shoppersDesc: [
    "شوف صفقات المتاجر حولك مرتّبة حسب المسافة.",
    "تابع متاجرك وتوصلك عروضها الجديدة أول بأول.",
    "احفظ العرض اللي عجبك وارجع له قبل أن ينتهي.",
  ],
  shoppersShot: "لقطة من التطبيق — العروض المحفوظة والمتاجر المتابَعة",
  // shops
  shopsTitle: "للمتاجر",
  shopsHeadline: "خلّي زبائن منطقتك يشوفونك",
  shopsPoints: ["انشر عروضك مجاناً", "وصول للزبائن في منطقتك", "تنبيه فوري لمتابعيك"],
  shopsDesc: [
    "أضف عرضك بصورة وسعر بدقائق، بدون أي رسوم.",
    "زبائن منطقتك يشوفون متجرك وهم يتصفّحون العروض القريبة.",
    "كل عرض جديد يصل متابعينك بإشعار فوري.",
  ],
  shopsShot: "لقطة من التطبيق — لوحة المتجر ونشر عرض جديد",
  shopsCta: "سجّل متجرك",
  // how it works
  howTitle: "كيف يعمل",
  howSteps: ["حمّل التطبيق", "تصفّح العروض حولك", "تابع، احفظ، واستفد"],
  howDesc: [
    "نزّل التطبيق على أندرويد بضغطة واحدة.",
    "افتح الخريطة وشوف العروض الأقرب لك.",
    "تابع متاجرك، احفظ العروض، واستفد قبل أن تنتهي.",
  ],
  // download
  downloadTitle: "حمّل التطبيق",
  androidNote: "متاح حالياً على أندرويد فقط.",
  sideloadNote: "بعد التحميل، اسمح بالتثبيت من «مصدر غير معروف» لإكمال التثبيت.",
  playSoon: "قريباً على Google Play",
  qrHint: "امسح للتحميل",
  checksumLabel: "بصمة الملف (SHA-256):",
  // contact
  contactTitle: "تواصل معنا",
  contactTelegram: "تيليغرام",
  contactWhatsapp: "واتساب",
  // footer
  privacy: "سياسة الخصوصية",
  terms: "شروط الاستخدام",
  rights: "© يلا مكسب",
  // admin
  adminTitle: "لوحة الإدارة",
  adminEmailLabel: "البريد الإلكتروني",
  adminSendLink: "أرسل رمز الدخول",
  adminLinkSent: "تفقّد بريدك — أرسلنا رمز الدخول.",
  adminCodeLabel: "رمز الدخول",
  adminVerify: "تأكيد الدخول",
  adminNotAuthorized: "هذا الحساب ليس مخوّلاً للدخول إلى لوحة الإدارة.",
  adminPendingTitle: "متاجر بانتظار الموافقة",
  adminEmpty: "لا توجد متاجر بانتظار الموافقة.",
  adminApprove: "موافقة",
  adminReject: "رفض",
  adminSignOut: "تسجيل الخروج",
  adminError: "حدث خطأ، حاول مرة أخرى.",
  adminFeedbackTab: "الملاحظات",
  adminPendingTab: "المتاجر",
  adminFeedbackTitle: "ملاحظات المستخدمين",
  adminFeedbackEmpty: "لا توجد ملاحظات.",
  adminFeedbackResolve: "تمّت المعالجة",
  adminFeedbackReopen: "إعادة فتح",
  adminFeedbackResolved: "معالَجة",
} as const;
